# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kiran/Projects/fpgaProjects/EmbeddedSystemDesign/mio_gpio/mio_gpio_vivado/mio_gpio_vivado.srcs/sources_1/bd/mio_gpio/ip/mio_gpio_processing_system7_0_0/mio_gpio_processing_system7_0_0.xci
# IP: The module: 'mio_gpio_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kiran/Projects/fpgaProjects/EmbeddedSystemDesign/mio_gpio/mio_gpio_vivado/mio_gpio_vivado.gen/sources_1/bd/mio_gpio/ip/mio_gpio_processing_system7_0_0/mio_gpio_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mio_gpio_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/kiran/Projects/fpgaProjects/EmbeddedSystemDesign/mio_gpio/mio_gpio_vivado/mio_gpio_vivado.srcs/sources_1/bd/mio_gpio/ip/mio_gpio_processing_system7_0_0/mio_gpio_processing_system7_0_0.xci
# IP: The module: 'mio_gpio_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kiran/Projects/fpgaProjects/EmbeddedSystemDesign/mio_gpio/mio_gpio_vivado/mio_gpio_vivado.gen/sources_1/bd/mio_gpio/ip/mio_gpio_processing_system7_0_0/mio_gpio_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mio_gpio_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
