# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/mio_gpio/mio_gpio.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mio_gpio || ORIG_REF_NAME==mio_gpio} -quiet] -quiet

# IP: bd/mio_gpio/ip/mio_gpio_processing_system7_0_0/mio_gpio_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mio_gpio_processing_system7_0_0 || ORIG_REF_NAME==mio_gpio_processing_system7_0_0} -quiet] -quiet

# XDC: /home/kiran/Projects/fpgaProjects/EmbeddedSystemDesign/mio_gpio/mio_gpio_vivado/mio_gpio_vivado.gen/sources_1/bd/mio_gpio/mio_gpio_ooc.xdc
